# After changing this file, check it on:
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
    - python: 3.6

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

# Build out environment
  - conda create -n janus python=3.6 psi4 psi4-rt numpy openmm -c psi4 -c omnia
  - source activate janus 
  - conda list

# Install various required modules
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov pytest-datafiles
  - pip install codecov
  - pip install mendeleev
  - conda install -c conda-forge mdtraj 
  - pip install Sphinx

# Install the plugin locally
  - pip install -e .

before_script:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'

script:
  - pytest -v --cov=./

# after_success:
#   - ./tools/travis-upload-wheel.sh

notifications:
    email: false

after_success:
  - codecov -t 323513ae-80cb-4c43-ab5c-49c962f3e9a6
